[workspace]
members = [
    "zusi-result-lib",
    "zusi-result-cli",
]
resolver = "2"

[workspace.package]
version = "0.1.7"
edition = "2024"

[workspace.dependencies]
clap = "4.5"
colored = "3.0"
glob = "0.3"
time = { version = "0.3" }
zusi-xml-lib = { path = "../zusi-xml-lib" }

[profile.dev]
debug = 'line-tables-only'

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
