[package]
name = "zusi-result-cli"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
glob.workspace = true
zusi-result-lib = { path = "../zusi-result-lib" }
zusi-xml-lib.workspace = true
